name:                ml-parser
version:             0.1.0.0
github:              "calin1304/ml-parser"
license:             BSD3
author:              "Calin Nicolau"
maintainer:          "calin.nicolau@gmail.com"
copyright:           "2020 Calin Nicolau"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/calin1304/ml-parser#readme>

# Make sure to also add extension to .stylish-haskell
default-extensions:
- BlockArguments
- DataKinds
- DeriveGeneric
- DerivingStrategies
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- TypeApplications

dependencies:
- base >= 4.7 && < 5
- array
- containers
- extra
- generic-lens
- lens
- mtl
- pretty
- QuickCheck
- text

build-tools:
- alex
- happy

library:
  source-dirs: src

ghc-options:
- -Wall
- -Werror
- -Wmissing-export-lists
- -Wmissing-import-lists

executables:
  ml-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ml-parser

tests:
  ml-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ml-parser
    - tasty
    - tasty-hunit
    - tasty-quickcheck
